### ISSUE TITLE
AirflowDB never recovers out of failed state

### ISSUE THREAD

**Issue by sbernauer** [stackabletech/airflow-operator#259]
Same as https://github.com/stackabletech/superset-operator/issues/351, it has the details

**Comment by fhennig** [comment]
> Just let the commands run in parallel

Maybe fine, is that what we settled on in Superset as well? I can't remember. I think it's a bit hacky but if it works, maybe that's the simplest way to do it.

> Run them only in the "Scheduler" Pod, since it should always be present exactly once.

Not comfortable with _should_. I think it would make sense to maybe consider this actually, how many schedulers can there be? Is there a high-availability configuration for Airflow with multiple schedulers?

> Since we loop over the roles in the code anyway, run the commands only in the first role that is parsed.

i'd be annoyed with the unpredictability of this. I think then i#d rather have it with the scheduler. I'm pretty sure you need at least 1 scheduler for the whole thing to work.

**Comment by dervoeti** [comment]
Sounds good :slightly_smiling_face:
Multiple schedulers should not be a problem for this. With Superset, multiple replicas are not a problem either, because we force them to start after another with the `OrderedReady` PodManagementPolicy. We can do the same for the Airflow scheduler. With Superset, we pretty much implemented it the same way, because Superset only has one role. With Airflow we need to limit it to it to one role (scheduler in this case) to achieve the same.

**Comment by fhennig** [comment]
Yeah I think that's what I'd go with, stick it in the scheduler and use orderedReady. it's more an implementation detail so we can change it later without breaking API comaptibility or stuff like that if we find out it's not the best way to do it.

**Comment by maltesander** [comment]
Yeah im for running it on the scheduler with orderedReady.

**Comment by dervoeti** [comment]
That was also my preferred solution, thanks for your feedback! I'll implement it like that.
