### ISSUE TITLE
Manually trigger db init job 

### ISSUE THREAD

**Issue by juliakroeberbtg** [stackabletech/airflow-operator#350]
### Affected version

all

### Current and expected behavior

We had a running and correctly deployed Airflow Cluster, however we wanted to update the root user password due to security concerns. In order to do that, we deleted all airflow related resources incl. the associated pvcs on the cluster and redeployed airflow. Unfortunately, all airflow pods (webserver, scheduler, worker pods) are not properly starting up and return the Error: DB needs to be initialized, run 'airflow db init'. As none of the pods are running we cannot shell into them to initialize the db. To the best of our knowledge the init job is only executed once.

Expected behaviour:
manually trigger db init job after airflow has been deployed once before.

### Environment

Airflow Version: 2.6.1

IONOS Managed Stackable: 23.7

### Would you like to work on fixing this bug?

None

**Comment by dervoeti** [comment]
Hi,
yes, sorry, this sounds like a bug we ran into before, and it will be fixed in our upcoming SDP release (23.11). You most likely have to delete the `AirflowDB` resource as well: `kubectl get airflowdbs.airflow.stackable.tech` and delete the listed resource (`kubectl delete airflowdbs.airflow.stackable.tech ...`). Then the init job should automatically be created.

We changed the overall logic and removed the AirflowDB resource completely in 23.11, so this should not happen in the future.
